version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    depends_on:
      - db
  db:
    image: mongo:4.4
    volumes:
      - db-data:/data/db
volumes:
  db-data: